# -*- coding: utf-8 -*-
"""Guardrail against Hallucinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1rJ0T4eXC2Y0s6u5OA5JVZ03B7jbO4k
"""

def hallucination_check(context, model_answer):
    print(f"Verifying: '{model_answer}' against known facts...")
    verification_prompt = f"""
    Fact: {context}
    AI Response: {model_answer}
    Does the AI response contain information NOT present in the Fact? (Yes/No)
    """ # Close the f-string here
    return True # Placeholder for logi

context_data = "The company was founded in 2010."
generated_text = "The company was founded in 2010 in New York."