# -*- coding: utf-8 -*-
"""Guardrail against Irrelevant Responses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pN7Jy3jFvxb-ZWHFbZAGlMcLGS1Vf8n6
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def relevance_guardrail(user_query, allowed_topics):
    vectorizer = TfidfVectorizer().fit(allowed_topics + [user_query])
    vectors = vectorizer.transform(allowed_topics + [user_query])

    # Compare user query against allowed topics using cosine similarity
    similarities = cosine_similarity(vectors[-1], vectors[:-1])

    if similarities.max() < 0.2: # Threshold for relevance
        return False, "I'm sorry, I can only discuss AI and Business Analytics."
    return True, "Relevant"

# Define your project scope
allowed = ["artificial intelligence", "machine learning", "business analytics", "python programming"]
user_input = "How do I bake a chocolate cake?"

is_relevant, message = relevance_guardrail(user_input, allowed)
print(message)